### ISSUE TITLE
Two issues (backpack and spy menu)

### ISSUE THREAD

**Issue by jas1992fasola** [Hypnootize/Hypnotize-m0rehud#4]
Concise disguise menu doesn't have numbers under classes and backpack buttons (A & D) are switched.
![image](https://user-images.githubusercontent.com/42492735/54560532-d5be1c80-49c2-11e9-9c41-17d287f26943.png)
![20190318211341_1](https://user-images.githubusercontent.com/42492735/54560552-de165780-49c2-11e9-9176-16862560c0b7.jpg)
![20190318211343_1](https://user-images.githubusercontent.com/42492735/54560553-de165780-49c2-11e9-8ac8-aa3f0a6f17a9.jpg)

**Comment by Hypnootize** [comment]
Fixed both thank you!
