### ISSUE TITLE
"Join" button is mispositioned

### ISSUE THREAD

**Issue by b7a** [Hypnootize/Hypnotize-m0rehud#7]
In regards to the "Your party is in a match" popup... https://imgur.com/DrbD41J

**Comment by Hypnootize** [comment]
I don't really use this so could you confirm if its fixed or not whenever you want? 
I moved it down for about 4 pixels from MatchMakingDashboard.res > "JoinNowButton" > "ypos" "rs1-5" was 9 before just in case its still too high and you wanna give it a go!

**Comment by b7a** [comment]
I found that the Join button would look best at rs1-3, as well as QueueText and PromptText being at ypos 2 instead of 1.

**Comment by Hypnootize** [comment]
I added the changes, thank you once again! 🙂
