### ISSUE TITLE
PvPRankPanel fonts

### ISSUE THREAD

**Issue by b7a** [Hypnootize/Hypnotize-m0rehud#8]
With some help from peaches, I was able to figure out that in order to fix the match summary XP bar, the DescLine1 and DescLine2 fonts should be:
```
	"0"		"HudFontMediumBigBold"
	"1"		"StorePromotionsTitle"
	"2"		"FontStorePrice"
```

**Comment by Hypnootize** [comment]
I kinda forgot this problem even existed, I fixed it with a different method but still everything looks good now.
